### ISSUE TITLE
Suspicious files found in the 1.2.0 tarball

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/oscap-anaconda-addon#164]
Hi @matejak , I have downloaded oscap-anaconda-addon-1.2.0.tar.gz from https://github.com/OpenSCAP/oscap-anaconda-addon/releases/download/r1.2.0/oscap-anaconda-addon-1.2.0.tar.gz and I can see some files in the `org_fedora_oscap` directory which I can't find in the git repository when I check out the git tag r1.2.0: bh.py, common.py.orig, dsh.py, model_ext.py.

**Comment by matejak** [comment]
This is a release glitch, but a harmless one, those files are not imported. We should adopt Github Actions to perform future releases automatically.

**Comment by matejak** [comment]
This is fixed in the 1.2.1 release.
