### ISSUE TITLE
Broken Testing doc

### ISSUE THREAD

**Issue by Frodox** [OpenSCAP/oscap-anaconda-addon#2]
[Here](https://fedorahosted.org/oscap-anaconda-addon/) is testing documentation:
```
curl http://vpodzime.fedorapeople.org/oscap_ana_addon_boot_0.6.iso.xz|unxz -T$(getconf _NPROCESSORS_ONLN) > oscap_addon_boot_0.6.iso
```
But it gets an error:
```
unxz: (stdin): File format not recognized
```
because there is force SSL redirect to `https` site version on https://fedorahosted.org
```
curl http://vpodzime.fedorapeople.org/oscap_ana_addon_boot_0.6.iso.xz
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://vpodzime.fedorapeople.org/oscap_ana_addon_boot_0.6.iso.xz">here</a>.</p>
</body></html>
```

So, somewho should fix the URL in docs :)

**Comment by vpodzime** [comment]
Good catch, thanks! The documentation is about to be moved to a new location so I'll make sure this gets fixed during the move.

**Comment by ybznek** [comment]
Thank you, it is fixed now.

We can close this as fixed (I don't have permissions)

**Comment by Frodox** [comment]
Just test it. Works :)
