### ISSUE TITLE
Fedora package ownership

### ISSUE THREAD

**Issue by evgenyz** [OpenSCAP/oscap-anaconda-addon#254]
Hey, @vpodzime!

Can you please transfer the Fedora package ownership to me (evgenyz)? It is being orphaned ATM because of lack of activity from the owner.

**Comment by vpodzime** [comment]
Hi! I surely can! I didn't even notice it was orphaned. Sorry about that.

**Comment by vpodzime** [comment]
Should be done now, @evgenyz. It's interesting that https://src.fedoraproject.org/rpms/oscap-anaconda-addon says nothing about it being orphaned and I found nothing at fedora-devel either. Where did you see it? (just for the future reference)

**Comment by evgenyz** [comment]
> Should be done now, @evgenyz. 

Thanks!

> It's interesting that https://src.fedoraproject.org/rpms/oscap-anaconda-addon says nothing about it being orphaned and I found nothing at fedora-devel either. Where did you see it? (just for the future reference)

https://pagure.io/find-inactive-packagers/issue/2149

**Comment by vpodzime** [comment]
Thanks! I find it strange that I see no traces of that in my inbox, but that's a separate story.
