### ISSUE TITLE
Use SSG datastreams instead of SSG XCCDFs

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/oscap-anaconda-addon#41]
When user customizes SSG profiles in SCAP Workbench, he customizes datastreams. When he saves tailoring file, he the file references the datastream. That's a complication when he will want to use it in OSCAP Anacoda Addon via kickstart, because OSCAP Anaconda Addon uses XCCDFs instead, so the  the original profile will not be found, and empty profile will be applied as a result.

**Comment by jan-cerny** [comment]
Relates to https://bugzilla.redhat.com/show_bug.cgi?id=1479008

**Comment by redhatrises** [comment]
I would say that we need to support either XCCDF or datastream just in case on a XCCDF file exists.

**Comment by jan-cerny** [comment]
Is there anything in SSG that exists only as XCCDF?

**Comment by yuumasato** [comment]
Build system of SSG generate XCCDF and DataStream files for all products.
Ultimately it is up to the package to carry them to the system, in case o RHEL and Fedora both file types are installed.
