### ISSUE TITLE
Method PasswdRules.eval_rules() ignores report_only parameter

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/oscap-anaconda-addon#52]
In
https://github.com/OpenSCAP/oscap-anaconda-addon/blob/rhel7-branch/org_fedora_oscap/rule_handling.py#L444
`report_only` parameter is ignored.

It looks to me that it should change the values of variables only if `report_only` is `True`.

Could be related to https://bugzilla.redhat.com/show_bug.cgi?id=1374181

**Comment by redhatrises** [comment]
Closing per PR #53
