### ISSUE TITLE
Update OAA GUI

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/oscap-anaconda-addon#60]
Current GUI of oscap-anaconda-addon is not really useful for level of content SSG provides. Profiles are listed in one widget, one after another, so user needs to scroll through all descriptions before it gets the profile it seeks. No way to skip to the desired one immediately.

Expected results:
* profiles can be selected from list of titles
* profile description is easy to read
* deselection is made by same button selection was made
* changes done / needed can be skimmed through easily

See https://bugzilla.redhat.com/show_bug.cgi?id=1472443

**Comment by matejak** [comment]
We would need some kind of UI design for this.
The box with changes was redesigned to be taller, but selection of profiles is problematic. https://github.com/OpenSCAP/oscap-anaconda-addon/pull/113 attempts to address this, but it has not been universally accepted.
