### ISSUE TITLE
RHEL 7.3 beta error: install crashes when using oscap-anaconda

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/oscap-anaconda-addon#7]
If you select a security profile in the RHEL 7.3 beta installer, the system crashes.

Screen shots:
![image](https://cloud.githubusercontent.com/assets/5713754/18063079/1b0764d4-6def-11e6-8a77-b409b0a9e96d.png)

![image](https://cloud.githubusercontent.com/assets/5713754/18063091/30e142b6-6def-11e6-9b1a-bb79e4c591f5.png)

![image](https://cloud.githubusercontent.com/assets/5713754/18063102/3d80b312-6def-11e6-93cc-295e8073f135.png)

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/18063112/4e14c790-6def-11e6-8972-ed11bf53b9ac.png)

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/18063125/5b70bb06-6def-11e6-8fdd-d0da1a099990.png)

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/18063136/6ba5bc06-6def-11e6-9600-99927a0851d4.png)

**Comment by vpodzime** [comment]
Should be fixed by https://github.com/OpenSCAP/oscap-anaconda-addon/commit/fb9c485418e59cfead3ab28d8ff8cfb7a19bba48
