### ISSUE TITLE
The file:// URI is not supported in the oscap GUI spoke.

### ISSUE THREAD

**Issue by matejak** [OpenSCAP/oscap-anaconda-addon#79]
Although we have pieces of support for fetching local filesystem content (i.e. `file:///usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`), it doesn't work from the gui.

* [_curl_fetch](https://github.com/OpenSCAP/oscap-anaconda-addon/blob/rhel7-branch/org_fedora_oscap/data_fetch.py#L119) internally supports the `file://` URI.
* [can_fetch_from](https://github.com/OpenSCAP/oscap-anaconda-addon/blob/rhel7-branch/org_fedora_oscap/data_fetch.py#L73) also supports the `file://` URI.
* [_fetch_data_and_initialize](https://github.com/OpenSCAP/oscap-anaconda-addon/blob/rhel7-branch/org_fedora_oscap/gui/spokes/oscap.py#L314-L350) doesn't, because it [skips all non-network URIs](https://github.com/OpenSCAP/oscap-anaconda-addon/blob/rhel7-branch/org_fedora_oscap/gui/spokes/oscap.py#L324).

**Comment by mpreisler** [comment]
Doesn't fetch_data skip over it because you don't need to fetch something that's local?

**Comment by matejak** [comment]
Maybe that was the thinking behind it, but the `_fetch_data_and_initialize` is the only related function that is called from `on_fetch_button_clicked`, so if it is skipped there, it is not carried out anywhere else. It is confusing that you need to call `_curl_fetch` to fetch a local file, which has nothing to do with `curl`.

**Comment by matejak** [comment]
Closed by #148
